apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rc5hsw3w2-go
  janus-idp.io/tekton: rc5hsw3w2-go
  backstage.io/kubernetes-id: rc5hsw3w2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rc5hsw3w2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
